import Link from "next/link";
import { auth } from "../_lib/auth";

export const metadata = {
  title: "Guest area",
  // description: 'Generated by Next.js',
};

export default async function Page() {
  const session = await auth();
  const firstName = session.user.name.split(" ").at(0);

  return (
    <div>
      <h2 className="font-semibold text-2xl text-accent-400 mb-7">
        Welcome {firstName}
      </h2>

      <Link href="/cabins">Explore luxury cabins</Link>
    </div>
  );
}
